### ISSUE TITLE
Ignore declare statements in "es-x/no-class-fields"

### ISSUE THREAD

**Issue by bhsd-harry** [eslint-community/eslint-plugin-es-x#100]
Hi! I am using this helpful plugin for my TypeScript project targeting browsers that support ES2018. Therefore, class fields should be disallowed. However, for the purpose of explicit type checking, a statement starting with the `declare` keyword in TypeScript won't be compiled into JavaScript eventually, which means it can be safely ignored by the `no-class-fields` rule. Is it possible that the plugin can detect the `declare` keyword and skip the line? Thanks!

**Comment by ota-meshi** [comment]
Sounds good to me. We welcome pull requests to make that change.
