### ISSUE TITLE
String trimStart/End doesn't detect the left/right aliases

### ISSUE THREAD

**Issue by robatwilliams** [eslint-community/eslint-plugin-es-x#119]
The rule `no-string-prototype-trimstart-trimend` doesn't detect the `trimLeft()` and `trimRight()` aliases.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd

**Comment by ota-meshi** [comment]
Use the `es-x/no-string-prototype-trimleft-trimright` rule instead.
https://eslint-community.github.io/eslint-plugin-es-x/rules/no-string-prototype-trimleft-trimright.html

**Comment by robatwilliams** [comment]
Thanks, didn't notice that one in the legacy section.

**Comment by robatwilliams** [comment]
This rule is failing with `Error: Rules with suggestions must set the `meta.hasSuggestions` property to `true`.`

It appears to be due to https://eslint.org/docs/latest/use/migrate-to-8.0.0#suggestions

**Comment by ota-meshi** [comment]
I don't really understand that error. The rule has hasSuggestions 🤔 

https://github.com/eslint-community/eslint-plugin-es-x/blob/f31a4aac8444e35eb20da962e87a230fd6e5c8ad/lib/rules/no-string-prototype-trimleft-trimright.js#L30

**Comment by robatwilliams** [comment]
Ah it's actually my mistake. I proxied from my own rule to this rule, so my own rule now needs to declare hasSuggestions=true

Apologies for the confusion.
