### ISSUE TITLE
'no-class-fields' work not good for firefox@75

### ISSUE THREAD

**Issue by xiaoxianjie** [eslint-community/eslint-plugin-es-x#134]
[Instance public fields](https://exploringjs.com/impatient-js/ch_classes.html#instance-public-fields) supported from firefox@69
[Static public fields](https://exploringjs.com/impatient-js/ch_classes.html#static-public-fields) supported from firefox@45

my browserslist: ['firefox >= 75']

but, the code below
```js
class {
  a = 1;
  static b = 2;
}
```
it will throw some errors as `ES2022 field 'a' is forbidden.`, `ES2022 static field 'b' is forbidden.`

i need only to disable the `private_class_field`s and `private_class_methods`;

**Comment by ota-meshi** [comment]
This plugin does not refer to browserlist, config your preferences yourself.

**Comment by xiaoxianjie** [comment]
Maybe my words made you misunderstand.
i mean's，
this rule can be spilt?
then, i can enable public property and disable the private property.

**Comment by ota-meshi** [comment]
Ah, I see. I think rule splitting is possible, but I think it needs to be done in major versions.
What "syntax" units do you think would be useful to split rules into in order to control compatibility with Firefox, other browsers, and Node.js?
Could you please open a new issue and suggest?
