### ISSUE TITLE
Rules for disallowing completely non-existent methods

### ISSUE THREAD

**Issue by zloirock** [eslint-community/eslint-plugin-es-x#181]
It's strange that we can forbid the usage of something like `'string'.isWellFormed()`, but can't disallow completely non-existent, like `'string'.fooBar()`, that are missed in any version of the spec.

Mabe make sense to add a set of rules for that?

**Comment by ota-meshi** [comment]
I think it would be useful for people to have that.
But I still don't know how to collect the properties/methods that exist in a good way.
Some TypeScript definitions don't have the properties defined in Annex B, or they have the properties in Stage 3.
Is parsing ECMA-262 the only way? 🤔

**Comment by zloirock** [comment]
I think that even manual adding of methods is fine - it's not such a big number of methods and is updated not so often. For early stage proposals should be added an option with lists of allowed methods.

**Comment by ota-meshi** [comment]
Thanks for the comment. I have started implementing the rules.
