### ISSUE TITLE
Only new APIs are banned, but not new syntax.

### ISSUE THREAD

**Issue by gwsbhqt** [eslint-community/eslint-plugin-es-x#99]
I used typescript and esbuild to compile down to es2018, so I can allow new syntax but not new APIs. For example: can use new syntax such as?. and??, but not APIs such as findLast or toReseve.

I am currently using plugin: es-x/restrict-to-es2018, which disables all new syntax and new APIs. Is there such a configuration that only disables new APIs, but not new syntax?

**Comment by ota-meshi** [comment]
> Is there such a configuration that only disables new APIs, but not new syntax?

That preset config is not provided by this plugin.
You have to create that config yourself or look for a preset config that someone has made.
